//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 GateF.rc 使用
//
#define IDP_OLE_INIT_FAILED             100
#define ID_SHELLCODE_VIEW               101
#define IDD_GATEF_DIALOG                102
#define IDC_SCREENSHOT_BUTTON           103
#define IDC_REFRESH_USERS_BUTTON        105
#define IDC_PROCESS_BUTTON              106
#define ID_SERVICE_REMOVE_CFG           108
#define ID_SERVICE_REMOVE_PLUGIN        109
#define ID_SERVICE_UPLOAD_CFG           110
#define ID_SERVICE_ALL_UPLOAD_CFG       111
#define ID_SERVICE_UPLOAD_PLUGIN        112
#define IDC_LOG_BUTTON                  113
#define ID_SERVICE_ADD_LIST             114
#define ID_SERVICE_CLEAR_LIST           115
#define IDR_MAINFRAME                   116
#define IDR_MAINFRAME1                  116
#define IDR_ACCELERATOR1                117
#define IDD_DIALOG1                     118
#define IDD_DIALOG_GAMES                119
#define IDD_DIALOG_ANTICHEAT            120
#define IDD_DIALOG_POLICES              121
#define IDD_SEARCHBAR                   122
#define IDD_DIALOG_LOG                  123
#define IDD_DIALOG_LOG_OBSERVER_CLIENT  124
#define IDR_MENU_USERS_RIGHT            125
#define IDR_SETING_RIGHT_MENU           127
#define IDD_DIALOG_LOG_OBC_SERVICE      128
#define IDD_DIALOG_LOG_OBC_LOGIC        129
#define IDD_DIALOG_PROCESSINFO          130
#define IDR_MENU_WHITE_LIST             136
#define IDI_ICON1                       137
#define IDI_ICON_RED                    137
#define IDI_ICON2                       139
#define IDI_ICON_BLUE                   141
#define IDC_TAB_MAIN                    1001
#define IDC_EDIT_POLICY_ID              1002
#define IDC_EDIT_POLICY_CONFIG          1003
#define IDC_LIST2                       1004
#define IDC_EDIT_POLICY_COMMENT         1005
#define IDC_BUTTON_REFRESH              1006
#define IDC_COMBO_POLICY_TYPE           1007
#define IDC_BUTTON2                     1008
#define IDC_COMBO_PUNISH_TYPE           1009
#define IDC_COMBO_PUNISH_TYPE2          1010
#define IDC_BUTTON_POLICY_COMMIT        1011
#define IDC_EXPDATE_STATIC              1012
#define IDC_BUTTON_SEARCH               1013
#define IDC_EDIT_SEARCH                 1014
#define IDC_RICHEDIT2_LOG_OBC_LOGIC     1015
#define IDC_EXPDATE_TEXT_STATIC         1016
#define IDC_LIST_GAMES                  1017
#define IDC_CHECK1                      1018
#define IDC_LIST_MODULEINFO             1019
#define IDC_CHECK2                      1020
#define IDC_LIST_THREADINFO             1021
#define IDC_TAB_LOG                     1022
#define IDC_LIST_THREADINFO2            1022
#define IDC_CHECK4                      1023
#define IDC_CHECK_BASE_POLICY           1024
#define IDC_CHECK5                      1025
#define IDC_RICHEDIT2_LOG_OBC           1026
#define IDC_CHECK6                      1027
#define IDC_CHECK_BETTER_POLICY         1028
#define IDC_CHECK7                      1029
#define IDC_EDIT_BACK                   1030
#define IDC_LIST_WHITE_MACHINA          1031
#define IDC_EDIT_POLICY_DETECT_INTERVAL 1032
#define IDC_CHECK_EXIT                  1033
#define IDC_STATIC_POLICY_INTERVAL1     1033
#define IDC_LIST_BLACK_MACHINE          1034
#define IDC_EDIT_EXIT                   1035
#define IDC_LIST_WHITE_IP               1036
#define IDC_CHECK_SPEED_WALK            1037
#define IDC_LIST_BLACK_IP               1038
#define IDC_EDIT_SPEED_WALK             1039
#define IDC_LIST_WHITE_ROLENAME         1040
#define IDC_TAB1                        1041
#define IDC_CHECK_SPEED_HIT             1042
#define IDC_LIST_BLACK_ROLENAME         1043
#define IDC_LIST_PROCESSINFO            1044
#define IDC_EDIT_SPEED_HIT              1045
#define IDC_CHECK_SPEED_SPELL           1046
#define IDC_EDIT_SPEED_SPELL            1047
#define IDC_CHECK_CAN_BACK_EXIT         1048
#define IDC_RICHEDIT2_LOG_OBC_SERVICE   1049
#define IDC_LIST_POLICES                1050
#define IDC_CHECK_BEST_POLICY           1051
#define IDC_CHECK3                      1052
#define IDC_CHECK_BACK                  1053
#define IDC_BUTTON4                     1054
#define ID_PROCESS_NAME                 1055
#define ID_PROCESS_PATH                 1056
#define ID_GET_GAMEUSER_FILE            1057
#define IDR_PROCESS_RIGHT_MENU          1058
#define IDC_LIST_DIRECTORYINFO          1059
#define IDC_STATIC_POLICY_INTERVAL      1060
#define IDC_SPIN_POLICY_DETECT_INTERVAL 1061
#define IDC_LIST_WHITE_MACHINE          1062
#define IDC_LIST_EDIT                   10010
#define IDC_LIST_COMBOBOX_POLICY        10011
#define IDC_LIST_COMBOBOX_PUNISH        10012
#define ID_32772                        32772
#define ID_REMOVE_FROM_WHITELIST        32773
#define ID_32774                        32774
#define ID_ROLENAME_BAN                 32775
#define ROLENAME                        32776
#define ID_ROLENAME_WHITE_ADD           32777
#define ID_PROCESS_VIEW                 32781
#define ID_WINDOWS_VIEW                 32782
#define ID_EXIT_GAME                    32783
#define ID_REFRESH_USERS                32786
#define ID_DRIVER_VIEW                  32787
#define ID_SCREENSHOT_VIEW              32788
#define ID_CFG_ADD                      32789
#define ID_CFG_DEL                      32790
#define ID_CFG_SAVE                     32791
#define ID_MAC_BAN                      32792
#define ID_IP_BAN                       32793
#define ID_MAC_WHITE_ADD                32794
#define ID_IP_WHITE_ADD                 32795
#define ID_INDICATOR_SERVER_STAUS       32796
#define ID_INDICATOR_USERS_COUNT        32797
#define ID_SERVICE_START                32798
#define ID_SERVICE_STOP                 32799
#define ID_COPY_MODULE_NAME             32800
#define ID_COPY_THREAD_ENTRY            32801
#define ID_COPY_FILE_NAME               32802
#define ID_COPY_MODULE_PATH             32803

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1034
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
