//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Gate.rc 使用
//
#define MINOR_VERSION                   0
#define INNER_VERSION                   0
#define MAJOR_VERSION                   1
#define IS_UNCOMMITED_VER               1
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDS_MAINFRAME_TITLE             102
#define IDD_PROP_EDIT_VIEW              103
#define IDD_SEARCHBAR                   104
#define IDD_MAINBAR                     105
#define IDS_STATUS_PANE1                106
#define IDS_STATUS_PANE2                107
#define IDS_TOOLBAR_STANDARD            108
#define IDS_TOOLBAR_CUSTOMIZE           109
#define IDR_MAINFRAME                   110
#define IDS_STRING_PROCESS_EXT          111
#define IDR_GateTYPE                    112
#define ID_WINDOW_MANAGER               113
#define IDS_STRING_DRIVER_EXT           114
#define IDS_STRING_WINDOW_EXT           115
#define IDS_STRING_CMD_EXT              116
#define IDS_STRING_CONFIG_EXT           117
#define ID_VIEW_OUTPUTWND               118
#define IDS_CLASS_VIEW                  119
#define IDS_OUTPUT_WND                  120
#define IDI_FILE_VIEW                   121
#define IDI_FILE_VIEW_HC                122
#define IDI_CLASS_VIEW                  123
#define IDI_CLASS_VIEW_HC               124
#define IDI_OUTPUT_WND                  125
#define IDI_OUTPUT_WND_HC               126
#define IDI_PROPERTIES_WND              127
#define IDI_PROPERTIES_WND_HC           128
#define IDB_EXPLORER_24                 129
#define IDB_SORT_24                     130
#define IDB_FILE_VIEW                   131
#define IDB_FILE_VIEW_24                132
#define IDB_CLASS_VIEW                  133
#define IDB_CLASS_VIEW_24               134
#define IDB_MENU_IMAGES_24              135
#define IDR_MENU_OUTPUT                 136
#define IDB_PROPERTIES_HC               137
#define REV_VERSION                     138
#define IDS_BUILD_TAB                   139
#define IDS_DEBUG_TAB                   140
#define IDS_FIND_TAB                    141
#define IDS_EXPLORER                    142
#define IDS_EDIT_MENU                   143
#define IDR_MENU_WINDOW                 144
#define IDD_OUTPUT_DIALOG               145
#define IDD_CONFIG_DIALOG               146
#define IDI_ICON_GUARD                  147
#define IDR_MENU_USERS_RIGHT            148
#define IDR_PROCESS_RIGHT_MENU          149
#define IDR_MODULE_RIGHT_MENU           150
#define IDR_MENU_HELP                   151
#define IDR_SETING_RIGHT_MENU           152
#define IDC_ABOUT_VERSION               1000
#define IDC_EDIT_POLICY_ID              1001
#define IDC_EDIT_POLICY_CONFIG          1002
#define IDC_EDIT_POLICY_COMMENT         1003
#define IDC_COMBO_POLICY_TYPE           1004
#define IDC_COMBO_PUNISH_TYPE           1005
#define IDC_BUTTON_POLICY_COMMIT        1006
#define IDC_REFRESH_USERS_BUTTON        1007
#define IDC_BUTTON_SEARCH               1008
#define IDC_SCREENSHOT_BUTTON           1009
#define IDC_EDIT_SEARCH                 1010
#define IDC_LOG_BUTTON                  1011
#define IDC_EXPDATE_STATIC              1012
#define IDC_EXPDATE_TEXT_STATIC         1013
#define IDC_REFRESH_LICENSE_BUTTON      1014
#define IDC_CHECK_BACK                  1015
#define IDC_EDIT_BACK                   1016
#define IDC_REFRESH_LICENSE_BUTTON2     1017
#define IDC_PROCESS_BUTTON              1018
#define IDC_CHECK_EXIT                  1019
#define IDC_EDIT_EXIT                   1020
#define IDC_CHECK_SPEED_WALK            1021
#define IDC_EDIT_SPEED_WALK             1022
#define IDC_CHECK_SPEED_HIT             1023
#define IDC_EDIT_SPEED_HIT              1024
#define IDC_CHECK_SPEED_SPELL           1025
#define IDC_EDIT_EXIT3                  1026
#define IDC_EDIT_SPEED_SPELL            1027
#define IDC_CHECK_EXIT2                 1028
#define IDC_CHECK_CAN_BACK_EXIT         1029
#define ID_TOOLBAR_START                32771
#define ID_TOOLBAR_STOP                 32772
#define ID_SERVICE_START                32773
#define ID_SERVICE_STOP                 32774
#define ID_PROCESS_VIEW                 32775
#define ID_WINDOWS_VIEW                 32776
#define ID_CLOSE_SOCKET                 32777
#define ID_EXIT_GAME                    32778
#define ID_MAC_VIEW                     32780
#define ID_IP_VIEW                      32781
#define ID_MODULE_NAME                  32782
#define ID_MODULE_PATH                  32783
#define ID_PROCESS_NAME                 32784
#define ID_PROCESS_PATH                 32785
#define ID_REFRESH_USERS                32786
#define ID_SERVICE_SETTINGS             32787
#define ID_DRIVER_VIEW                  32788
#define ID_SCREENSHOT_VIEW              32789
#define ID_BUTTON32797                  32790
#define ID_ACCELERATOR32798             32791
#define ID_SHELLCODE_VIEW               32792
#define ID_CMD_VIEW                     32793
#define ID_CFG_ADD                      32794
#define ID_CFG_DEL                      32795
#define ID_CFG_SAVE                     32796
#define ID_MAC_BAN                      32797
#define ID_IP_BAN                       32798
#define ID_32807                        32799
#define ID_32808                        32800
#define ID_32809                        32801
#define ID_MAC_WHITE_ADD                32802
#define ID_IP_WHITE_ADD                 32803
#define ID_SERVICE_REFRESH              32804
#define ID_SERVICE_UPDATE_LOGIC         32805
#define ID_SERVICE_UPLOAD_CFG           32806
#define ID_SERVICE_REMOVE_CFG           32807
#define ID_SERVICE_UPLOAD_PLUGIN        32808
#define ID_SERVICE_REMOVE_PLUGIN        32809
#define ID_JS_QUERY_DEVICE_ID           32810
#define ID_JS_EXECUTE                   32811
#define ID_SERVICE_ADD_LIST             32812
#define ID_SERVICE_CLEAR_LIST           32813
#define ID_SERVICE_S2C_PLUGIN           32814
#define ID_WINDOW_TITLE                 32815
#define ID_WINDOW_CLASS_NAME            32816
#define ID_WINDOW_BOTH                  32817
#define ID_SERVICE_ALL_UPLOAD_CFG       32818
#define ID_TOOLBAR_CONFIG               32819
#define ID_VIEW                         32820
#define ID_INDICATOR_SERVER_STAUS       32821
#define ID_INDICATOR_USERS_COUNT        32822

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        331
#define _APS_NEXT_COMMAND_VALUE         32828
#define _APS_NEXT_CONTROL_VALUE         1015
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
