//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Gate.rc 使用
//
#define MINOR_VERSION                   0
#define INNER_VERSION                   0
#define MAJOR_VERSION                   1
#define IS_UNCOMMITED_VER               1
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_MAINFRAME_TITLE             101
#define IDD_PROP_EDIT_VIEW              101
#define IDD_SEARCHBAR                   102
#define IDD_MAINBAR                     103
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define IDR_MAINFRAME                   128
#define IDS_STRING_PROCESS_EXT          129
#define IDR_GateTYPE                    130
#define ID_WINDOW_MANAGER               131
#define IDS_STRING_DRIVER_EXT           132
#define IDS_STRING_WINDOW_EXT           133
#define IDS_STRING_CMD_EXT              134
#define IDS_STRING_CONFIG_EXT           135
#define ID_VIEW_OUTPUTWND               149
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDB_EXPLORER_24                 170
#define IDB_SORT_24                     172
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDB_MENU_IMAGES_24              180
#define IDR_MENU_OUTPUT                 182
#define IDB_PROPERTIES_HC               184
#define REV_VERSION                     202
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_MENU_WINDOW                 319
#define IDD_OUTPUT_DIALOG               323
#define IDD_CONFIG_DIALOG               325
#define IDI_ICON1                       328
#define IDI_ICON_GUARD                  328
#define IDI_config                      330
#define IDR_MENU1                       331
#define IDR_MENU_USERS_RIGHT            331
#define IDR_PROCESS_RIGHT_MENU          332
#define IDR_MODULE_RIGHT_MENU           333
#define IDR_MENU_HELP                   334
#define IDR_SETING_RIGHT_MENU           335
#define IDC_ABOUT_VERSION               1000
#define IDC_EDIT_POLICY_ID              1001
#define IDC_EDIT_POLICY_CONFIG          1002
#define IDC_EDIT_POLICY_COMMENT         1003
#define IDC_COMBO_POLICY_TYPE           1004
#define IDC_COMBO_PUNISH_TYPE           1005
#define IDC_BUTTON_POLICY_COMMIT        1006
#define IDC_REFRESH_USERS_BUTTON        1007
#define IDC_BUTTON_SEARCH               1008
#define IDC_SCREENSHOT_BUTTON           1009
#define IDC_EDIT_SEARCH                 1010
#define IDC_LOG_BUTTON                  1010
#define IDC_EXPDATE_STATIC              1011
#define IDC_EXPDATE_TEXT_STATIC         1012
#define IDC_REFRESH_LICENSE_BUTTON      1013
#define IDC_CHECK_BACK                  1013
#define IDC_EDIT_BACK                   1014
#define IDC_REFRESH_LICENSE_BUTTON2     1014
#define IDC_PROCESS_BUTTON              1014
#define IDC_CHECK_EXIT                  1015
#define IDC_EDIT_EXIT                   1016
#define IDC_CHECK_SPEED_WALK            1017
#define IDC_EDIT_SPEED_WALK             1018
#define IDC_CHECK_SPEED_HIT             1019
#define IDC_EDIT_SPEED_HIT              1020
#define IDC_CHECK_SPEED_SPELL           1021
#define IDC_EDIT_EXIT3                  1022
#define IDC_EDIT_SPEED_SPELL            1022
#define IDC_CHECK_EXIT2                 1023
#define IDC_CHECK_CAN_BACK_EXIT         1023
#define ID_TOOLBAR_START                32771
#define ID_TOOLBAR_STOP                 32772
#define ID_SERVICE_START                32775
#define ID_SERVICE_STOP                 32776
#define ID_PROCESS_VIEW                 32781
#define ID_WINDOWS_VIEW                 32782
#define ID_CLOSE_SOCKET                 32783
#define ID_EXIT_GAME                    32784
#define ID_MAC_VIEW                     32786
#define ID_IP_VIEW                      32787
#define ID_MODULE_NAME                  32788
#define ID_MODULE_PATH                  32789
#define ID_PROCESS_NAME                 32791
#define ID_PROCESS_PATH                 32792
#define ID_REFRESH_USERS                32793
#define ID_SERVICE_SETTINGS             32794
#define ID_DRIVER_VIEW                  32795
#define ID_SCREENSHOT_VIEW              32796
#define ID_BUTTON32797                  32797
#define ID_ACCELERATOR32798             32798
#define ID_SHELLCODE_VIEW               32800
#define ID_CMD_VIEW                     32801
#define ID_CFG_ADD                      32802
#define ID_CFG_DEL                      32803
#define ID_CFG_SAVE                     32804
#define ID_MAC_BAN                      32805
#define ID_IP_BAN                       32806
#define ID_32807                        32807
#define ID_32808                        32808
#define ID_32809                        32809
#define ID_MAC_WHITE_ADD                32810
#define ID_IP_WHITE_ADD                 32811
#define ID_SERVICE_REFRESH              32812
#define ID_SERVICE_UPDATE_LOGIC         32813
#define ID_SERVICE_UPLOAD_CFG           32814
#define ID_SERVICE_REMOVE_CFG           32815
#define ID_SERVICE_UPLOAD_PLUGIN        32816
#define ID_SERVICE_REMOVE_PLUGIN        32817
#define ID_JS_QUERY_DEVICE_ID           32818
#define ID_JS_EXECUTE                   32819
#define ID_SERVICE_ADD_LIST             32820
#define ID_SERVICE_CLEAR_LIST           32821
#define ID_SERVICE_S2C_PLUGIN           32822
#define ID_WINDOW_TITLE                 32823
#define ID_WINDOW_CLASS_NAME            32824
#define ID_WINDOW_BOTH                  32825
#define ID_SERVICE_ALL_UPLOAD_CFG       32826
#define ID_TOOLBAR_CONFIG               32827
#define ID_GM32828                      32828
#define ID_VIEW                         32829
#define ID_INDICATOR_SERVER_STAUS       59143
#define ID_INDICATOR_USERS_COUNT        59144

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        336
#define _APS_NEXT_COMMAND_VALUE         32830
#define _APS_NEXT_CONTROL_VALUE         1015
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
